# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskforge < Formula
  desc "Taskforge CLI"
  homepage "https://github.com/gentij/taskforge"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_darwin_amd64.tar.gz"
      sha256 "4c3047c9167112ed4ddf5cd45ef67e231bc02ad51966ca3385f4897279da6dfa"

      define_method(:install) do
        bin.install "taskforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_darwin_arm64.tar.gz"
      sha256 "1f2730088ff97faeb40f879389325e3f5887da6bf951510021322a33de2c3223"

      define_method(:install) do
        bin.install "taskforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_linux_amd64.tar.gz"
      sha256 "524e3f6a25a40cd1cf7d2009e422763062572ac71cd74cd414749e145d300b0b"
      define_method(:install) do
        bin.install "taskforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_linux_arm64.tar.gz"
      sha256 "5eb745009c8e5700acd9f59f08930071bebbbb9396b086d6b7d6dce296f27d9d"
      define_method(:install) do
        bin.install "taskforge"
      end
    end
  end
end
