# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskforge < Formula
  desc "Taskforge CLI"
  homepage "https://github.com/gentij/taskforge"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_darwin_amd64.tar.gz"
      sha256 "348ac9f3c1ff36030a243a523575f79c8600190ab4049c5ad28c467d829eb643"

      define_method(:install) do
        bin.install "taskforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_darwin_arm64.tar.gz"
      sha256 "279306d11f3646d859269e934e23de2d7487bf8b952edc186e8ea1da18add62e"

      define_method(:install) do
        bin.install "taskforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_linux_amd64.tar.gz"
      sha256 "87f40ac108862f996fcd3891b86b31d015a44cb076870f1c4dea0a9010813cb1"
      define_method(:install) do
        bin.install "taskforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_linux_arm64.tar.gz"
      sha256 "06c307d4de5bc9deefce775f6946feb6813ed27f5142bab6d7b8dc3eb209c6b8"
      define_method(:install) do
        bin.install "taskforge"
      end
    end
  end
end
