# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskforge < Formula
  desc "Taskforge CLI"
  homepage "https://github.com/gentij/taskforge"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_darwin_amd64.tar.gz"
      sha256 "12c8f6925eb4cbc3a12feed5586d2fb5851941f464e3a83cd63b9f8b03bba3f1"

      define_method(:install) do
        bin.install "taskforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_darwin_arm64.tar.gz"
      sha256 "e806ec0671a832721248b5bb49340061ae9c9faea0b41b4a763228f65e96b0fe"

      define_method(:install) do
        bin.install "taskforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_linux_amd64.tar.gz"
      sha256 "3795b563febed59a5cfb8ab456408e26fc7047590b2a9bab30904c5d57e1b54d"
      define_method(:install) do
        bin.install "taskforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_linux_arm64.tar.gz"
      sha256 "5c07a01abeb4e565dd987ebbfb458d2d0792a41b88dd72f67c44be33bd61c8e0"
      define_method(:install) do
        bin.install "taskforge"
      end
    end
  end
end
