# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskforge < Formula
  desc "Taskforge CLI"
  homepage "https://github.com/gentij/taskforge"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_darwin_amd64.tar.gz"
      sha256 "7b7ea054e9a19fd4e338694b4422ba44ad959d226323086cbf0dd15aa8c8b104"

      define_method(:install) do
        bin.install "taskforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_darwin_arm64.tar.gz"
      sha256 "5bde9700c940d88e3c519c7b8d7d1c0323c68c07b3ce58540f23c1fbccca3c77"

      define_method(:install) do
        bin.install "taskforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_linux_amd64.tar.gz"
      sha256 "899a277ca42411498207afe1667afa087d8de6ce716c4a93f6c85e0aead423b3"
      define_method(:install) do
        bin.install "taskforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gentij/taskforge/releases/download/v0.1.0/taskforge_linux_arm64.tar.gz"
      sha256 "2a308ff8da9fe6b6e9441f0bee7930c623c6c7276e77bcff57d66eea342994ab"
      define_method(:install) do
        bin.install "taskforge"
      end
    end
  end
end
